### ISSUE TITLE
Spark for iOS

### ISSUE THREAD

**Issue by mazurio** [robinhood/spark#12]
Hi guys,

First of all - great work! I have started using Spark in my project and love it.

I was wondering if you guys have "Spark" for iOS too that you are planning to open source or are you using something else for iOS?

Thanks,
Damian

**Comment by danh32** [comment]
Hey Damian,

Thanks so much!

Unfortunately, we don't have any immediate plans to open source the iOS equivalent. I'll definitely let the team know there's interest, though!

**Comment by mazurio** [comment]
Thanks @danh32 - I will be waiting for the update on it!

**Comment by smaguluri** [comment]
Hi guys,
          It's really awesome library for android. Any update on plans to open source the iOS equivalent?

**Comment by danh32** [comment]
@smaguluri thanks for the kind words! Our iOS app has switched over to using [this library](https://github.com/danielgindi/Charts), so there's no Spark equivalent for iOS.
