### ISSUE TITLE
Spark has trouble displaying time-series data

### ISSUE THREAD

**Issue by Azeirah** [robinhood/spark#16]
I've got some data like this, using UNIX timestamps as x-values, and arbitrary values as y-values.

```json
"dataPoints": {
   "1466546066": 2.0,
   "1466546068": 4.0,
   "1466546069": 2.0,
   "1466546070": 1.0,
   "1466546071": 3.0,
   "1466546072": 2.0,
   "1466546073": 4.0,
   "1466546304": 5.0,
   "1466546305": 4.0,
   "1466546306": 2.0,
   "1466546307": 3.0
}
```

The resulting sparkline looks like this, it really shouldn't look like that!

![sparky](https://cloud.githubusercontent.com/assets/4040870/16287429/3665aace-38e3-11e6-92d8-f8f77c4f6344.png)

It could be that I'm doing something wrong, though the sparkline shows correctly when I use indices going from 0-10 instead of using timestamps

This is my adapter

```java
public class TimedSparkAdapter extends SparkAdapter {

    private Double[] xData;
    private Double[] yData;

    public TimedSparkAdapter(Double[] xData, Double[] yData) {
        this.xData = xData;
        this.yData = yData;
    }

    @Override
    public int getCount() {
        return yData.length;
    }

    @Override
    public Double getItem(int index) {
        return yData[index];
    }

    @Override
    public float getY(int index) {
        return yData[index].floatValue();
    }

    @Override
    public float getX(int index) {
        return xData[index].floatValue();
    }
}
```

And this is what's in my layout

```xml
    <com.robinhood.spark.SparkView
        android:id="@+id/sparkline"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
```

**Comment by danh32** [comment]
Sorry for the delay! Was out on vacation.

I will look into this at some point this week. My first thought is perhaps a rounding issue since Spark is using floats for the x,y coords here. But those Y values look incorrect as well, so I'm not entirely sure.

**Comment by FabianTerhorst** [comment]
I think for timestamps the view needs a different way to calculate the distances between the value points. Maybe a  getX override method that needs a date object?

**Comment by Azeirah** [comment]
Ugh, sorry guys. I found out exactly why this graph appears the way it does.

My points on the x-line have a huge jump, notice halfway, instead of x-incrementing by 1 like it does all the time, it increments with ~230. Clumping all the first few values together on the left, and the other half on the right. I noticed this when I enlarged the graph by a lot.

```
  "1466546073": 4.0,
  "1466546304": 5.0,
```

![graph](https://cloud.githubusercontent.com/assets/4040870/16635321/240f9746-43d2-11e6-8bcd-c85446eae87a.PNG)

This library is working as expected, the data was at fault.

**Comment by danh32** [comment]
No worries, thanks for the follow up!

**Comment by Azeirah** [comment]
Thinking about it a bit more, even though this representation is technically _correct_, it's not very _helpful_ to the viewer, is it? Should an alternative representation be used when cases like these are detected? Stem graphs would work a little bit better in this case for example.

**Comment by Azeirah** [comment]
The larger graph would look like this

![stem-lg](https://cloud.githubusercontent.com/assets/4040870/16636194/e38649d6-43d6-11e6-8ca7-deba6e8ef799.PNG)

The sparkstem could look like this, it's a lot clearer.

![stem-sm](https://cloud.githubusercontent.com/assets/4040870/16636195/e389a054-43d6-11e6-8e53-264428888687.PNG)

Not sure if it would be worth the time implementing all heuristics needed to decide what kind of plot to use however, I'm not even sure if that can be reliably done. Or if it is even within the scope of this project.

**Comment by danh32** [comment]
This seems outside of the scope of Spark to me, since it's no longer a sparkline chart. I also don't think many apps that use Spark would want this behavior. And as you mentioned, detecting this case reliably is quite difficult.

I think Spark should maintain the current behavior, and apps can use custom logic in their SparkAdapters to massage the data however they might want.

**Comment by Azeirah** [comment]
Thought so, thanks for taking the time to discuss this issue
