### ISSUE TITLE
ScrubWidth is using LineWidth in Constructor

### ISSUE THREAD

**Issue by zoltish** [robinhood/spark#17]
When you initialize the scrubPaint you use this: 

`sparkLinePaint.setStrokeWidth(lineWidth);
`

It should be using the **scrubLineWidth** variable instead. 

Thanks for the great library! :)

**Comment by danh32** [comment]
Thanks! Just pushed a fix. If you need it asap, you should be able to use the snapshot release. I'll do a full release in a couple of weeks.
