### ISSUE TITLE
[REQUEST] iOS and React Native

### ISSUE THREAD

**Issue by JSafaiyeh** [robinhood/spark#29]
Wondering if there is a plan to release this on iOS and/or React Native.

**Comment by danh32** [comment]
Hi,

Sorry, no plans currently. I will let the iOS team know there is interest, though!

**Comment by JSafaiyeh** [comment]
Awesome. Definetly would like a consistent UI, across both clients.

**Comment by JSafaiyeh** [comment]
Any update on the iOS version? If it were to be released, I could get started on making the react-native bridge.

**Comment by danh32** [comment]
Hi @JSafaiyeh, our iOS team has recently migrated to using [this library](https://github.com/danielgindi/Charts) for charting. Apparently it was based off of [MPAndroidChart](https://github.com/PhilJay/MPAndroidChart), so maybe those libs would work for you?

**Comment by JSafaiyeh** [comment]
Oh cool! Yeah, MPAndroidChart and Chart were on my possible libraries to use.
Good to know nice graphs can be made with them. Thanks!
