### ISSUE TITLE
Allow different fill color to spark line color

### ISSUE THREAD

**Issue by RichyHBM** [robinhood/spark#37]
As title suggests, it should be possible to get the fill drawing with a different color to the main line.

I have managed to get this working locally, with a subclass of spark view, and wondered if it would be worth porting it back into Spark and submitting a PR?

**Comment by danh32** [comment]
Sure! As long as it works backwards compatibly with the current fill feature, this sounds good!

**Comment by RichyHBM** [comment]
Cool. Whilst doing this work I also found it quite hard to have a subclass of SparkView because a lot of the things that I needed were marked as private, so if you think its OK I may also submit another PR with some things changed to protected?
