### ISSUE TITLE
Proposal: Rename stylable tag to SparkView.

### ISSUE THREAD

**Issue by naturalwarren** [robinhood/spark#43]
When writing layout XML library consumers don't get autocomplete on `SparkView`'s stylable attributes. We had a similar problem in Ticker [#75](https://github.com/robinhood/ticker/issues/75).

Can we rename the stylable tag to SparkView? This change should be compile time safe and prompt folks to update their XML/source.

**Comment by danh32** [comment]
Yep, I'd love to get autocomplete working!

**Comment by danh32** [comment]
Closed in #44
