### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by CurtJRees** [robinhood/spark#57]
Will there be a new release soon, the current version (1.2.0) doesn't seem to work with fillType
And the code hosted here appears to be much more up to date

**Comment by CurtJRees** [comment]
Apologies, this appeared to be an issue with my getX function

**Comment by danh32** [comment]
No worries, we are overdue for a release. Hoping to get at it soon!

**Comment by Sub6Resources** [comment]
Any progress on a release @danh32 ?

**Comment by danh32** [comment]
@Sub6Resources sorry for the delay! have been out on vacation. I will try to get a release out this week and look through the PRs here.
