### ISSUE TITLE
question : support gradient color ?

### ISSUE THREAD

**Issue by shakeri-mreza** [robinhood/spark#59]

**Comment by danh32** [comment]
Hi @shakeri-mreza - I'm working on a way to allow generic drawing effects and going to be tracking that work here: https://github.com/robinhood/spark/issues/63

Once that's in place, I can add gradient support fairly easily.

**Comment by danh32** [comment]
I should have mentioned, in the meantime, you can achieve gradients like this:

```
    final SparkView sparkView = findViewById(R.id.sparkview);
    sparkView.setFillType(SparkView.FillType.DOWN);
    final Paint fillPaint = sparkView.getSparkFillPaint();
    fillPaint.setShader(new LinearGradient(...));
```
