### ISSUE TITLE
Show min and max values.

### ISSUE THREAD

**Issue by pkhivesara** [robinhood/spark#61]
Does the library support showing max and min values from a given data set onto the sparkView? Something similar to what the Coinbase android app does?
I am attaching an image below:

<img width="449" alt="screen shot 2018-04-12 at 5 15 54 pm" src="https://user-images.githubusercontent.com/6237488/38704766-5dab5bf8-3e75-11e8-8788-dc333edadd49.png">

In the image we can see two bubbles which denote the high and lows for the selected day. 

Any recommendation on how to achieve it?

Thanks!

**Comment by naturalwarren** [comment]
I think you could use the `getScaledX()` and `getScaledY()` APIs on `SparkView` to determine where to draw your min/max labels. By default `SparkAdapter.getDataBounds()` gives you back the min and max data points in your adapter.

**Comment by pkhivesara** [comment]
I did find those methods..However even after getting the floating value point how i can actually add an UI element to the exisiting sparkView graph? For example: is there a method such a ```sparkView.setTextView(string value, float x)``` or something along those lines? I am lost at how to update the sparkView class with a new label.

**Comment by naturalwarren** [comment]
Awesome! Now you'll want to instantiate a `TextView` programmatically and position it using the scaled x and y values returned from your `SparkView`. SparkView is just a [Sparkline](https://en.wikipedia.org/wiki/Sparkline) so it doesn't provide the ability to add labels.

**Comment by pkhivesara** [comment]
I tried the approach that you suggested. However from the documentation it seems like the ```SparkView``` doesn't really use the ```x-axis``` co-ordinates. It divides ```the x-axis``` equally and simply draws a ```Path``` along the ```y-axis```. That being said, wouldn't the ```getScaledX()``` return me a pixel which is not actually used by the ```SparkView```. If i try the aforementioned approach, the text is not visible at all, however if i only use the ```getScaledY()``` and then use ```text.setY(float y)``` i see can see the text on the top left corner since that is the highest value.

Apologies if this is getting out of hand.

**Comment by danh32** [comment]
Hi @pkhivesara,

@naturalwarren is right, we don't support this out of the box, but you should be able to roll-your-own here.

The x-axis behavior you mentioned can be changed. If you want spark to use the x values from your data, you can override `getX()` in your SparkAdapter.

So after doing that, you can getScaledX/Y to find the spark-local coordinates of the min and max points in your data. You should be able to use those to position a TextView however you'd like. Or you could even subclass SparkView itself and draw text directly to the canvas in onDraw().

This is a fair amount of work, though, and I believe MpAndroidChart likely supports this out of the box: https://github.com/PhilJay/MPAndroidChart

**Comment by pkhivesara** [comment]
I am not sure but whenever i try to use the approach mentioned above, the text is always displayed either on top left or top right. It seems like the layout is being added against the screen width and height. Not the SparkView itself. Either ways i understand since this requirement is not part of SparkView, i will be closing the ticket. Thanks for all the help.!
