### ISSUE TITLE
Make use of Android annotations more consistent throughout library

### ISSUE THREAD

**Issue by cammace** [robinhood/spark#62]
Capturing from @naturalwarren, The annotations introduced in https://github.com/robinhood/spark/pull/55 are useful and we could expand on this with the addition of other annotations on the public APIs.

**Comment by cammace** [comment]
https://github.com/robinhood/spark/pull/65 seems to have added some `@nonNull` checks, not sure if that qualifies for this issue being closed or not @naturalwarren.

**Comment by naturalwarren** [comment]
Oh yeah, whoops, sorry I forgot to link this issue. Lets close it!

**Comment by danh32** [comment]
Thanks, @naturalwarren !
