### ISSUE TITLE
Fill with gradient

### ISSUE THREAD

**Issue by FrostRocket** [robinhood/spark#69]
Is it possible to create a fill gradient for spark instead of filling with a solid color?

**Comment by danh32** [comment]
Yeah, you can grab a reference to the fill paint and set a linear gradient:

    final SparkView sparkView = findViewById(R.id.sparkview);
    sparkView.setFillType(SparkView.FillType.DOWN);
    final Paint fillPaint = sparkView.getSparkFillPaint();
    fillPaint.setShader(new LinearGradient(...));

**Comment by winnerawan** [comment]
@danh32 there's not method getSparkFillPaint

**Comment by danh32** [comment]
It should be right here:
https://github.com/robinhood/spark/blob/master/spark/src/main/java/com/robinhood/spark/SparkView.java#L598
