### ISSUE TITLE
Not showing baseline with just getBaseLine()

### ISSUE THREAD

**Issue by johanneslagos** [robinhood/spark#7]
I don't know if it is a bug, but the baseline is not show until you overwrite hasBaseline().

**Comment by danh32** [comment]
This is working as intended: you do need to override both methods in order to show a baseline.

**Comment by johanneslagos** [comment]
Yes. But your documentation only talks about override of getBaseline() ;)

**Comment by danh32** [comment]
Oops, good call! We will update asap!

**Comment by danh32** [comment]
Just added to the readme. Thanks for the report!
