### ISSUE TITLE
BaseLine dotted line sample

### ISSUE THREAD

**Issue by singh029** [robinhood/spark#70]
I'm having trouble creating the baseline in the sparkview when following the [blog post here](https://robinhood.engineering/introducing-spark-dc17269b83f6). Could you please provide a sample on getting this setup and how to get it to appear on the price point of the first tick.

**Comment by danh32** [comment]
To get the baseline to show up, in your SparkAdapter you need to do:

```
override boolean hasBaseLine() {
    return true;
}

override float getBaseLine() {
    return baseLinePoint;
}
```
where `baseLinePoint` is wherever in your data that you want the baseLine to show up.

Hope that helps!

**Comment by singh029** [comment]
Awesome! it works great! i just had to assign a value to baseLinePoint and set the baseline length and spacing correctly.
        Paint baseLinePaint = sparkview.getBaseLinePaint();
        DashPathEffect dashPathEffect = new DashPathEffect(new float[] {**2, 10**}, 0);
        baseLinePaint.setPathEffect(**dashPathEffect**);
