### ISSUE TITLE
Thank you..

### ISSUE THREAD

**Issue by erluxman** [robinhood/spark#71]
So I have never opened an issue to thank on github, I thought this might be a bad idea and people might be angry at me for using issue for these kind of things. But I got a feeling that this project deserves an alteration to the conventions. 

Most of the time we need just the simple, beautiful and peaceful stuffs just like lying upside in the middle of lake(thats how I define peace) and this library is one of those. And this looks like that library I am going to use in every single graphing project.

I hope I will be able to contribute to this project also once I find some shortcomings, but for now it's amazing. 

Thank you again, the team @Robinhood

**Comment by danh32** [comment]
Hi @erluxman

Thanks so much for the kind words -- I'm really glad you like the library! Definitely let us know if you have any feedback or find any issues!
