### ISSUE TITLE
Why doesn't onScrubbed include both x and y?

### ISSUE THREAD

**Issue by JBlaz** [robinhood/spark#72]
Just curious why there isn't a listener for both the x and y values?

**Comment by JBlaz** [comment]
That's a great point. I asked my question incorrectly. I guess I want to know the index of the value as well as the value. Or just the index then I can get the value.

**Comment by danh32** [comment]
`SparkView` calls `ScrubListener.onScrubbed()` with the return value from `SparkAdapter.getItem(nearestIndex)`:
https://github.com/robinhood/spark/blob/master/spark/src/main/java/com/robinhood/spark/SparkView.java#L910

Maybe you can make your `getItem()` return the generic item that you want?

**Comment by JBlaz** [comment]
I apologize for wasting anyone's time who read this. So obvious! Thank you @danh32. For some reason in my head it wasn't returning an object it was returning a float.

**Comment by JBlaz** [comment]
Me too. Thanks again!
