### ISSUE TITLE
Conditionally color sparkline

### ISSUE THREAD

**Issue by DZehden** [robinhood/spark#76]
I've noticed on the Robinhood app that scrubbing over portions of the sparkline that are after-hours will tint market and pre-market hour portions to a darker color while keeping the scrubbed over region the same. Is this conditional tinting possible with the default sparkview and if so, is there any guidance as far as coloring or tinting regions of the sparkline based on adapter data?

**Comment by danh32** [comment]
Unfortunately, it's not easily achievable using Spark. We've got some custom internal modifications that made this possible, but didn't clean up well enough to be able to push to Spark. We hope to do this eventually, but likely won't be any time soon.
