### ISSUE TITLE
Android graph mismatch to actual charting data

### ISSUE THREAD

**Issue by antoniobeltran** [robinhood/spark#77]
I don't know if this is the right spot for this...

1 - On Android Robinhood, my charting appears to not match actual history. On the full history chart, it appears I was up 100% over all for a few months in 2018 which it wasn't. I see this hasn't changed in a while so maybe it's something related to another part of the project, or this needs to be updated to reflect some changes on another branch? This started happening on Monday/Tuesday 4/13/20 - 4/14/20

2 - On Android Robinhood, when you see notifications for % gain or loss, you see a red bear chart for a gain and a green bull chart for a loss. The graphics should be reversed.  I can take a look at this repo for that is you want. 

These could be issues on another repo, and this chart is just reading it as is.

**Comment by danh32** [comment]
Hi Antonio,

Unfortunately, neither of these is related to the Spark library.

1) This is likely an issue with the historical data we're getting from the server. I'm not sure a good way to fix, these glitches often disappear on their own after a couple of days.

2) If you're talking about the chart emoji in the notification text itself, we don't have control over those. For whatever reason, the "chart with upwards trend" emoji is red on most platforms (https://emojipedia.org/chart-increasing/).
